#!/usr/bin/env bash
set -euo pipefail

# Build the portable TTT-Discover runtime image.
# Override IMAGE_TAG or BASE_IMAGE from the shell.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

IMAGE_TAG="${IMAGE_TAG:-open-ttt-verl:ttt-vllm}"
BASE_IMAGE="${BASE_IMAGE:-verlai/verl:vllm017.latest}"
DOCKERFILE="${DOCKERFILE:-docker/Dockerfile.ttt-vllm}"
CONTEXT="${CONTEXT:-${REPO_ROOT}}"
REBUILD_FLASH_ATTN="${REBUILD_FLASH_ATTN:-1}"
FLASH_ATTN_VERSION="${FLASH_ATTN_VERSION:-2.8.3}"
FLASH_ATTN_CUDA_ARCHS="${FLASH_ATTN_CUDA_ARCHS:-100}"
FLASH_ATTN_TORCH_CUDA_ARCH_LIST="${FLASH_ATTN_TORCH_CUDA_ARCH_LIST:-10.0}"
FLASH_ATTN_MAX_JOBS="${FLASH_ATTN_MAX_JOBS:-8}"
FLASH_ATTN_NVCC_THREADS="${FLASH_ATTN_NVCC_THREADS:-4}"
FLASH_ATTN_CUDA_HOME="${FLASH_ATTN_CUDA_HOME:-}"

cd "${REPO_ROOT}"

docker build \
  --build-arg "BASE_IMAGE=${BASE_IMAGE}" \
  --build-arg "REBUILD_FLASH_ATTN=${REBUILD_FLASH_ATTN}" \
  --build-arg "FLASH_ATTN_VERSION=${FLASH_ATTN_VERSION}" \
  --build-arg "FLASH_ATTN_CUDA_ARCHS=${FLASH_ATTN_CUDA_ARCHS}" \
  --build-arg "FLASH_ATTN_TORCH_CUDA_ARCH_LIST=${FLASH_ATTN_TORCH_CUDA_ARCH_LIST}" \
  --build-arg "FLASH_ATTN_MAX_JOBS=${FLASH_ATTN_MAX_JOBS}" \
  --build-arg "FLASH_ATTN_NVCC_THREADS=${FLASH_ATTN_NVCC_THREADS}" \
  --build-arg "FLASH_ATTN_CUDA_HOME=${FLASH_ATTN_CUDA_HOME}" \
  -f "${DOCKERFILE}" \
  -t "${IMAGE_TAG}" \
  "$@" \
  "${CONTEXT}"
