#!/bin/bash
set -euo pipefail

IMAGE=${IMAGE:-open-ttt-slime:latest}
REPO_DIR=${REPO_DIR:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)}
WORKSPACE_HOST=${WORKSPACE_HOST:-${REPO_DIR}/workspace}
CONTAINER_NAME=${CONTAINER_NAME:-open-ttt-slime}
SHM_SIZE=${SHM_SIZE:-64g}
DOCKER_GPUS=${DOCKER_GPUS:-all}

mkdir -p \
  "${WORKSPACE_HOST}/models" \
  "${WORKSPACE_HOST}/ckpt" \
  "${WORKSPACE_HOST}/logs" \
  "${WORKSPACE_HOST}/data" \
  "${WORKSPACE_HOST}/tmp"

ENV_ARGS=(
  -e WORKSPACE=/root/workspace
  -e REPO_DIR=/root/workspace/erdos
  -e HF_HUB_ENABLE_HF_TRANSFER="${HF_HUB_ENABLE_HF_TRANSFER:-1}"
  -e HF_HUB_DISABLE_XET="${HF_HUB_DISABLE_XET:-1}"
)

add_env_if_set() {
  local name=$1
  if [ -n "${!name+x}" ]; then
    ENV_ARGS+=(-e "${name}=${!name}")
  fi
}

if [ -n "${HF_TOKEN:-}" ]; then
  ENV_ARGS+=(-e HF_TOKEN="${HF_TOKEN}")
fi
if [ -n "${HUGGING_FACE_HUB_TOKEN:-}" ]; then
  ENV_ARGS+=(-e HUGGING_FACE_HUB_TOKEN="${HUGGING_FACE_HUB_TOKEN}")
fi

for name in \
  LOG_ROOT MODEL_RAW MODEL_BF16 REF_CKPT SAVE_CKPT PROMPT_DATA ARCHIVE_PATH TTT_SANDBOX_WORK_DIR \
  TOTAL_GPUS ACTOR_NUM_GPUS ROLLOUT_NUM_GPUS ROLLOUT_NUM_GPUS_PER_ENGINE NUM_GPUS_PER_NODE COLOCATE \
  TENSOR_MODEL_PARALLEL_SIZE PIPELINE_MODEL_PARALLEL_SIZE CONTEXT_PARALLEL_SIZE \
  EXPERT_MODEL_PARALLEL_SIZE EXPERT_TENSOR_PARALLEL_SIZE \
  NUM_ROLLOUT START_ROLLOUT_ID ROLLOUT_BATCH_SIZE N_SAMPLES_PER_PROMPT GLOBAL_BATCH_SIZE MICRO_BATCH_SIZE \
  ROLLOUT_MAX_RESPONSE_LEN ROLLOUT_TEMPERATURE ROLLOUT_TOP_P SEQ_LENGTH MAX_POSITION_EMBEDDINGS MAX_TOKENS_PER_GPU \
  SAVE_INTERVAL LORA_RANK LORA_ALPHA LR KL_LOSS_COEF TTT_ENTROPIC_TARGET_KL \
  TTT_TARGET_C5 TTT_SANDBOX_TIMEOUT_S TTT_SANDBOX_CPUS \
  ADAM_BETA1 ADAM_BETA2 ADAM_EPS WEIGHT_DECAY \
  SGLANG_MEM_FRACTION_STATIC SGLANG_CONTEXT_LENGTH SGLANG_DISABLE_CUSTOM_ALL_REDUCE \
  MEGATRON_TO_HF_MODE INITIAL_WEIGHT_SYNC_TIMEOUT_S NCCL_NVLS_ENABLE \
  RAY_DASHBOARD_PORT MASTER_ADDR KILL_STALE_PROCESSES RUN_ID LOG_FILE TRAIN_LOG_FILE \
  MODEL_ID MODEL_ROOT MODEL_DIR CKPT_ROOT FORCE_DOWNLOAD CKPT_OUT NPROC FORCE_PREPROCESS FORCE_CONVERT; do
  add_env_if_set "${name}"
done

if [ "$#" -eq 0 ]; then
  CMD=(/bin/bash)
else
  CMD=("$@")
fi

if [ -t 0 ]; then
  TTY_ARGS=(-it)
else
  TTY_ARGS=(-i)
fi

docker run --rm "${TTY_ARGS[@]}" \
  --name "${CONTAINER_NAME}" \
  --gpus "${DOCKER_GPUS}" \
  --ipc=host \
  --shm-size "${SHM_SIZE}" \
  --ulimit memlock=-1 \
  --ulimit stack=67108864 \
  "${ENV_ARGS[@]}" \
  -v "${WORKSPACE_HOST}:/root/workspace" \
  -v "${REPO_DIR}:/root/workspace/erdos" \
  -w /root/workspace/erdos \
  "${IMAGE}" \
  "${CMD[@]}"
